name: Runner

on:
  push:
    branches: [ "main" ]

jobs:
  test-debian:
    runs-on: self-hosted
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Dire bonjour
        run: echo "Bonjour depuis ma VM Debian 13 !"

      - name: Vérifier l'heure de la VM
        run: date
